---

name: emails

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  bugzilla:
    runs-on: ubuntu-latest
    steps:
      - uses: nrwl/last-successful-commit-action@v1
        id: last_successful_commit
        with:
          branch: 'dev'
          workflow_id: 'emails.yml'
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: dev
          fetch-depth: 0

      - uses: actions/setup-python@v3
        with:
          python-version: 3.x

      - name: Validate compare commit
        run: |
          if git rev-parse --verify "${{ steps.last_successful_commit.outputs.commit_hash }}^{commit}"; then
            echo "is_commit_valid=true" >> ${GITHUB_ENV}
          else
            echo "is_commit_valid=false" >> ${GITHUB_ENV}
          fi

      - name: Get changed files
        id: changed-files
        if: ${{ fromJSON(env.is_commit_valid) }}
        uses: tj-actions/changed-files@v35
        with:
          base_sha: ${{ steps.last_successful_commit.outputs.commit_hash }}
          files: |
            **/metadata.xml

      - name: Check Emails against bugzilla
        if: ${{ fromJSON(env.is_commit_valid) }}
        run: |
          python ./scripts/email-checker.py ${{ steps.changed-files.outputs.all_changed_files }}

      - name: Inform on IRC
        if: ${{ failure() && github.repository == 'gentoo/guru' && github.event_name == 'push' }}
        uses: rectalogic/notify-irc@v1
        with:
          channel: "#gentoo-guru"
          server: "irc.libera.chat"
          nickname: "github-ci"
          message: CI failure detected on job ${{ github.workflow }} - ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
